# Generated by Django 3.2.6 on 2021-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_id_admin_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='CDMX', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='MX', max_length=3),
        ),
    ]
